name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build-haskell-image.yml
    strategy:
      matrix:
        ghc-version: [ '9.6.5', '9.2.8' ]
    with:
      ghc-version: ${{ matrix.ghc-version }}
