name: Build Haskell Image

on:
  workflow_call:
    inputs:
      ghc-version:
        description: 'GHC version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          build-args: |
            GHC=${{ inputs.ghc-version }}
          tags: |
            # latest tag for the default branch:
            type=raw,value=${{ inputs.ghc-version }},enable={{is_default_branch}}
      - name: ${{ github.ref == 'refs/heads/main' && 'Build and Push Docker image' || 'Build Docker image' }}
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main'}}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.docker-metadata.outputs.tags }}
          build-args: |
            GHC=${{ inputs.ghc-version }}
